/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libroundrobin_GestorProcesos */

#ifndef _Included_libroundrobin_GestorProcesos
#define _Included_libroundrobin_GestorProcesos
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libroundrobin_GestorProcesos
 * Method:    calculateProcessExecution
 * Signature: (I[I[I[I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_libroundrobin_GestorProcesos_calculateProcessExecution
  (JNIEnv *, jobject, jint, jintArray, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
